try {
    console,log("start try");
} catch (error) {
    console,log("error occured "+error);
} finally{
    console,log("this always runs");   
}